#=============================================#
#   Resolution Schemes
#=============================================#

temporal-scheme: euler                        # possible values: ['euler', 'ssp-rk2', 'imex']
spatial-scheme: hllc                          # possible values: ['hllc', 'muscl', 'low-froude']

#=============================================#
#   Input files
#=============================================#

mesh-file: docs/demo/mesh.geo                 #
boundary-condition-file: docs/demo/bc.txt     #
initial-state-file: docs/demo/dof_init.txt    #
hydrographs-file: docs/demo/hydrographs.txt   #
rating-curve-file: docs/demo/ratcurve.txt     #

bathymetry-file: bathymetry.txt               # UNUSED
manning-file: manning_from_file.txt           # UNUSED

#=============================================#
#   Resolution parameters
#=============================================#

simulation-time: 2000                         #
delta-to-write: 500                           #
is-delta-adaptive: false                      #
default-delta: 0.001                          # only used if 'is-delta-adaptive' is false

#=============================================#
#   Output specs
#=============================================#

result-path: ./outputs/                         #
output-mode: hdf5                             # possible values: ['vtk', 'tecplot', 'gnuplot', 'hdf5']
